# Matrices
Vamos a ver cómo crear una matriz utilizando la librería `numpy`.

In [2]:
import numpy as np

In [3]:
A = np.array([[1,2], [3,4]])
B = np.array([[3,0], [1,-1]])

In [4]:
A+B

array([[4, 2],
       [4, 3]])

In [5]:
A*B # Error

array([[ 3,  0],
       [ 3, -4]])

In [7]:
print(A.dot(B))

[[ 5 -2]
 [13 -4]]


In [8]:
print(A.transpose())

[[1 3]
 [2 4]]


In [9]:
print(A.trace())

5


In [10]:
np.linalg.matrix_rank(A)

2

In [11]:
np.linalg.matrix_power(A, 5)

array([[1069, 1558],
       [2337, 3406]])

In [12]:
np.linalg.det(A)

-2.0000000000000004

In [13]:
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
print(np.linalg.inv(A).dot(A))

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


In [15]:
X = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [17]:
np.linalg.det(X)

-9.51619735392994e-16

In [18]:
np.linalg.matrix_rank(X)

2

In [19]:
np.linalg.inv(X)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

No se nos ocurrirá nunca hacer la inversa ni de una matriz cuadrada, ni de una matriz cuyo rango sea inferior a su orden (el número de filas / columnas de la misma).

In [23]:
# np.linalg.inv(np.array([1,2,3], [4,5,6]))

In [24]:
X[0]

array([1, 2, 3])

In [25]:
for row in X:
    print(row[0])

1
4
7
